---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | default .Values.global.name }}
  namespace: {{ .Values.name | default .Values.global.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name | default .Values.global.name }}
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
