---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | default .Values.global.name }}
  namespace: {{ .Values.name | default .Values.global.name }}-{{ .Values.env | default .Values.global.env }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name | default .Values.global.name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
